source("R/landweber/functions.R")
source("R/landweber/mesh.R")
source("R/landweber/discretized_matrix.R")
source("R/landweber/discretized_right_hand_side.R")
source("R/landweber/formula_3_11.R")
source("R/landweber/formula_3_10.R")
source("R/landweber/iterative_procedure.R")
