source("R/landweber/functions.R")
source("R/landweber/mesh.R")
source("R/landweber/matrix.R")
source("R/landweber/right_hand_side.R")
source("R/landweber/discretized_matrix.R")
source("R/landweber/discretized_right_hand_side.R")
source("R/landweber/iterative_procedure.R")
